export default [
  {
    titleNO: "Friluftsskolen m/speideren",
    titleEN: "Outdoor school w/scouts",
    category: ["utendørs", "tur", "telt"],
    image:
      "https://melhus.speiding.no/wp-content/uploads/sites/269/2020/09/logoer.jpg",
    url: "https://melhus.speiding.no/friluftsskolen-2021-apent-for-pamelding/",
    date: "",
    week: 25,
    dateFirst: "21/05/2021",
    dateLast: "25/06/2021",
    time: "10:00",
    place: "Vassfjellet",
    target: ["1. - 4. klasse", "5. - 7. klasse"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Minecraft server",
    titleEN: "Minecraft server",
    category: ["ungdom", "barn", "innendørs", "aktivitet"],
    image:
      "https://usercontent.one/wp/www.playnordic.net/wp-content/uploads/2021/04/wp6308453-uai-1032x774.jpg",
    url: "https://www.playnordic.net/bli-med-hjemme-fra/",
    date: "",
    week: "",
    dateFirst: "21/05/2021",
    dateLast: "13/08/2021",
    time: "10:00",
    place: "Online",
    target: ["1. - 4. klasse", "5. - 7. klasse", "Ungdomsskole", "VGS"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Sommercamp m/Melhus Makers",
    titleEN: "Summercamp w/Melhus Makers",
    category: ["innendørs", "barn", "ungdom", "workshop"],
    image:
      "https://melhusmakers.no/____impro/1/onewebmedia/melhusmakers..png?etag=%2233c6-6089be42%22&sourceContentType=image%2Fpng&ignoreAspectRatio&resize=223%2B200&extract=0%2B0%2B223%2B200",
    url: "https://melhusmakers.no/sommercamp",
    date: "",
    week: "26-32",
    dateFirst: "28/06/2021",
    dateLast: "13/08/2021",
    time: "09:00",
    place: "Melhus sentrum",
    target: ["1. - 4. klasse", "5. - 7. klasse", "Ungdomsskole", "VGS"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Inspire Camp m/Drive for life",
    titleEN: "Inspire Camp w/Drive for life",
    category: ["utendørs", "lek", "barn"],
    image: "https://www.driveforlife.com/wp-content/uploads/2020/08/DSC09638-Usain-Bolt-1024x684.jpg",
    url: "https://www.driveforlife.com/inspire/",
    date: "",
    week: "25-32",
    dateFirst: "",
    dateLast: "",
    time: "",
    place: "Rundt omkring",
    target: ["5. - 7. klasse"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Magishow på Camp Melhus",
    titleEN: "Magic Show at Camp Melhus",
    category: ["show", "barn", "innendørs"],
    image: "https://www.driveforlife.com/wp-content/uploads/2020/08/DSC09638-Usain-Bolt-1024x684.jpg", // placeholder
    url: "https://campmelhus.hoopla.no/sales",
    date: "26/06/2021",
    week: "",
    dateFirst: "26/06/2021",
    dateLast: "26/06/2021",
    time: "",
    place: "Camp Melhus",
    target: ["1. - 4. klasse", "5. - 7. klasse"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Workshops på Rådhuset",
    titleEN: "Workshops  ",
    category: ["workshop", "ungdom", "innendørs"],
    image:
      "https://pbs.twimg.com/media/ElrfBetXEAUYdgb.jpg",
    url: "https://pbs.twimg.com/media/ElrfBetXEAUYdgb.jpg", // placeholder
    date: "01/01/2001", // placeholder
    week: "",
    dateFirst: "",
    dateLast: "",
    time: "10:00",
    place: "Rådhuset",
    target: [""],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Åpen scene",
    titleEN: "Open stage",
    category: ["show", "ungdom", "innendørs"],
    image:
      "https://scontent.ftrd4-1.fna.fbcdn.net/v/t1.6435-9/182448131_3049973961901191_6126678891131764987_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=jSXP-hoCcyQAX_wQt88&_nc_ht=scontent.ftrd4-1.fna&oh=70d82af1f1aba7620c65411388d489dd&oe=60DB8282",
    url: "https://scontent.ftrd4-1.fna.fbcdn.net/v/t1.6435-9/182448131_3049973961901191_6126678891131764987_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=jSXP-hoCcyQAX_wQt88&_nc_ht=scontent.ftrd4-1.fna&oh=70d82af1f1aba7620c65411388d489dd&oe=60DB8282", // placeholder
    date: "",
    week: "",
    dateFirst: "",
    dateLast: "",
    time: "0.75",
    place: "Rådhuset",
    target: "",
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Gaming-event",
    titleEN: "Gaming event",
    category: ["ungdom", "barn", "innendørs", "aktivitet"],
    image:
      "https://usercontent.one/wp/www.playnordic.net/wp-content/uploads/2021/05/IMG_6680-uai-1080x1440.png",
    url: "https://www.playnordic.net/",
    date: "",
    week: "28-29",
    dateFirst: "12/07/2021",
    dateLast: "23/07/2021",
    time: "10:00",
    place: "Rådhuset",
    target: ["5. - 7. klasse", "Ungdomsskole", "VGS"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },
  {
    titleNO: "Konsert med Rasmus Rohde og verdens beste band",
    titleEN: "Concert with Rasmus Rohde and the worlds best band",
    category: ["show", "barn", "innendørs"],
    image: "https://usercontent.one/wp/www.playnordic.net/wp-content/uploads/2021/05/IMG_6680-uai-1080x1440.png", // placeholder
    url: "https://campmelhus.hoopla.no/sales",
    date: "14/07/2021",
    time: "10:00",
    place: "Teltet",
    target: ["1. - 4. klasse", "5. - 7. klasse"],
    ctaNO: "Vis aktivitet",
    ctaEN: "View activity",
    horizontal: false,
    full: true,
    block: false,
  },

];
