export default [
  { id: "1", category: "target", titleEN: "1st - 4th grade", titleNO: "1. - 4. klasse" },
  { id: "2", category: "target", titleEN: "5th - 7th grade", titleNO:  "5. - 7. klasse" },
  { id: "3", category: "target", titleEN: "8th - 10th grade", titleNO:  "Ungdomsskole" },
  { id: "4", category: "target", titleEN: "11th - 13th grade", titleNO:  "VGS" },
  {
    id: "5",
    category: "place",
    titleEN: "Center",
    titleNO: "Sentrum",
  },
  {
    id: "6",
    category: "place",
    titleEN: "Districts",
    titleNO: "Distrikter",
  },
  { id: "7", category: "category", titleEN: "outdoors", titleNO: "utendørs" },
  { id: "8", category: "category", titleEN: "play", titleNO: "lek" },
 { id: "9", category: "category", titleEN: "youth", titleNO: "ungdom" },
 { id: "10", category: "category", titleEN: "kids", titleNO: "barn" },
 { id: "11", category: "category", titleEN: "indoors", titleNO: "innendørs" },
 { id: "12", category: "category", titleEN: "show", titleNO: "show" },
 { id: "13", category: "category", titleEN: "workshop", titleNO: "workshop" },
 { id: "14", category: "category", titleEN: "activity", titleNO: "aktivitet" },
 { id: "15", category: "category", titleEN: "animals", titleNO: "dyr" },
];
